### ISSUE TITLE
Obtaining Index Error using fPCA on Data Set

### ISSUE THREAD

**Issue by rswarnick1** [glemaitre/fdasrsf#2]
Hello, 

I'm receiving the following error when running the method on my data:

`IndexErrorTraceback (most recent call last)
<ipython-input-30-554c68119958> in <module>()
----> 1 fpca.align_fPCA(seis_trunc,time,showplot = False, smoothdata=True)

/hpcdata/warmhv/ENV_CONDA/Rypy2/lib/python3.5/site-packages/fdasrsf/time_warping.py in align_fPCA(f, time, num_comp, showplot, smoothdata)
    702     # Get Final PCA
    703     mididx = np.round(time.shape[0] / 2)
--> 704     m_new = np.sign(fn[mididx, :]) * np.sqrt(np.abs(fn[mididx, :]))
    705     mqn2 = np.append(mqn, m_new.mean())
    706     qn2 = np.vstack((qn, m_new))

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices'

Wondering what the issue is, or if it's something I can fix by adjusting my inputs.

**Comment by glemaitre** [comment]
This package is only a fork of the original package:

Try to use the original package:
https://github.com/jdtuck/fdasrsf_python

I forked it at the time because it was not available on GitHub.
